export interface LanguageOption {
  code: string;
  name: string;
  nativeName: string;
}

export const LANGUAGES_50: LanguageOption[] = [
  { code: "uz", name: "Uzbek", nativeName: "O'zbekcha" },
  { code: "uz-cyr", name: "Uzbek Cyrillic", nativeName: "Ўзбекча" },
  { code: "ru", name: "Russian", nativeName: "Русский" },
  { code: "en", name: "English", nativeName: "English" },
  { code: "tr", name: "Turkish", nativeName: "Türkçe" },
  { code: "kk", name: "Kazakh", nativeName: "Қазақша" },
  { code: "ky", name: "Kyrgyz", nativeName: "Кыргызча" },
  { code: "tg", name: "Tajik", nativeName: "Тоҷикӣ" },
  { code: "tk", name: "Turkmen", nativeName: "Türkmençe" },
  { code: "az", name: "Azerbaijani", nativeName: "Azərbaycanca" },
  { code: "de", name: "German", nativeName: "Deutsch" },
  { code: "fr", name: "French", nativeName: "Français" },
  { code: "es", name: "Spanish", nativeName: "Español" },
  { code: "it", name: "Italian", nativeName: "Italiano" },
  { code: "pt", name: "Portuguese", nativeName: "Português" },
  { code: "nl", name: "Dutch", nativeName: "Nederlands" },
  { code: "pl", name: "Polish", nativeName: "Polski" },
  { code: "ro", name: "Romanian", nativeName: "Română" },
  { code: "sv", name: "Swedish", nativeName: "Svenska" },
  { code: "no", name: "Norwegian", nativeName: "Norsk" },
  { code: "da", name: "Danish", nativeName: "Dansk" },
  { code: "fi", name: "Finnish", nativeName: "Suomi" },
  { code: "cs", name: "Czech", nativeName: "Čeština" },
  { code: "hu", name: "Hungarian", nativeName: "Magyar" },
  { code: "el", name: "Greek", nativeName: "Ελληνικά" },
  { code: "bg", name: "Bulgarian", nativeName: "Български" },
  { code: "uk", name: "Ukrainian", nativeName: "Українська" },
  { code: "be", name: "Belarusian", nativeName: "Беларуская" },
  { code: "ka", name: "Georgian", nativeName: "ქართული" },
  { code: "hy", name: "Armenian", nativeName: "Հայერեն" },
  { code: "ar", name: "Arabic", nativeName: "العربية" },
  { code: "fa", name: "Persian", nativeName: "فارسی" },
  { code: "he", name: "Hebrew", nativeName: "עברית" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা" },
  { code: "ur", name: "Urdu", nativeName: "اردو" },
  { code: "zh", name: "Chinese", nativeName: "中文" },
  { code: "ja", name: "Japanese", nativeName: "日本語" },
  { code: "ko", name: "Korean", nativeName: "한국어" },
  { code: "vi", name: "Vietnamese", nativeName: "Tiếng Việt" },
  { code: "th", name: "Thai", nativeName: "ไทย" },
  { code: "id", name: "Indonesian", nativeName: "Bahasa Indonesia" },
  { code: "ms", name: "Malay", nativeName: "Bahasa Melayu" },
  { code: "fil", name: "Filipino", nativeName: "Filipino" },
  { code: "sw", name: "Swahili", nativeName: "Kiswahili" },
  { code: "am", name: "Amharic", nativeName: "አማርኛ" },
  { code: "zu", name: "Zulu", nativeName: "isiZulu" },
  { code: "mn", name: "Mongolian", nativeName: "Монгол" },
  { code: "ne", name: "Nepali", nativeName: "नेपाली" },
  { code: "si", name: "Sinhala", nativeName: "සිංහල" }
];

export const UI_TRANSLATIONS: Record<string, Record<string, string>> = {
  uz: {
    brandName: "Uheyiluy Tuxumlari",
    heroBadge: "✨ Farg'ona bo'ylab tezkor yetkazib berish",
    heroTitle: "Toza va Shifobaxsh",
    heroTitleSpan: "Uheyiluy Tuxumlari",
    heroDesc: "Qora tovuqlardan olinadigan, tabiat mo'jizasi bo'lgan shifobaxsh moviy-yashil tuxumlar. Yoshlar rivojlanishi va keksalar salomatligi uchun bebahodir.",
    availableEggs: "dona mavjud",
    pricePerEgg: "so'm / dona",
    btnOrder: "🛒 Buyurtma qilish",
    btnPickup: "📍 Olib ketish",
    statsHenTitle: "Sog'lom tovuqlar",
    statsHenDesc: "Erkin parvarish",
    statsDeliveryTitle: "24/7 Xizmat",
    statsDeliveryDesc: "Tez yetkazib berish",
    statsStockTitle: "Zaxira",
    statsStockDesc: "Dona mavjud",
    whyUsTitle: "Nima uchun Uheyiluy?",
    whyUsSub: "Uheyiluy tuxumlarining oddiy tuxumdan afzalliklari",
    featHenTitle: "Tabiiy Erkin Tovuqlar",
    featHenDesc: "Faqat tabiiy dori-darmonsiz, yaylovda boqilgan Uheyiluy zotli qora tovuqlar.",
    featColorTitle: "Noyob Moviy Qobiq",
    featColorDesc: "Tuxum qobig'ining yashil-moviy rangi tabiiy bo'lib, yuqori mikroelementlar nishonidir.",
    featFastTitle: "Eshikkacha Yetkazish",
    featFastDesc: "Farg'ona bo'ylab buyurtmangizni ehtiyotkorlik bilan xonadoningizga eltib beramiz.",
    featPriceTitle: "Hamyonbop Narx",
    featPriceDesc: "Eng shifobaxsh tuxumlarni to'g'ridan-to'g'ri ishonchli qo'llardan hamyonbop narxda olasiz.",
    orderTitle: "Buyurtma yuborish",
    orderSub: "Quyidagi formani to'ldiring, tez orada siz bilan bog'lanamiz",
    emptyStockMsg: "😔 Hozircha tuxum qolmadi. Tez orada yangi tuxumlar keladi!",
    lowStockMsg: "⚠️ Kam qoldi! Buyurtma berishga shoshiling.",
    labelName: "Ismingiz",
    placeholderName: "Masalan: Alibek",
    labelPhone: "Telefon raqamingiz",
    placeholderPhone: "+998 XX XXX XX XX",
    labelAddress: "Yetkazib berish manzili",
    placeholderAddress: "Ko'cha, uy raqami, mahalla",
    btnLocateMap: "🗺️ Xaritadan",
    gmapSearchPlaceholder: "Manzilni kiriting va qidiring...",
    gmapConfirm: "✅ Tasdiqlash",
    labelQuantity: "Soni (Dona)",
    totalPayment: "Jami to'lov:",
    btnSubmitOrder: "✅ Buyurtma yuborish",
    btnSubmitting: "⏳ Yuborilmoqda...",
    toastSuccess: "✅ Buyurtma qabul qilindi! Tez orada bog'lanamiz 🎉",
    toastError: "❌ Iltimos, barcha maydonlarni to'ldiring!",
    toastLowStock: "⚠️ Uzr, zaxirada yetarli emas!",
    pickupTitle: "📍 Olib ketish manzili",
    pickupSub: "Bizning manzilimizga kelib, tuxumlarni o'zingiz olib ketishingiz mumkin",
    pickupCardTitle: "📌 Manzilimiz",
    btnCall: "📞 Qo'ng'iroq",
    btnGmaps: "Google Maps xaritasi",
    deliveryTitle: "Yetkazib berish jarayoni",
    deliverySub: "Sizning buyurtmangiz uyingizga qanday yetib boradi?",
    delStep1Title: "Buyurtma berish",
    delStep1Desc: "Saytdan yoki Telegram bot orqali buyurtma qoldirasiz.",
    delStep2Title: "Bog'lanish",
    delStep2Desc: "Operatorimiz buyurtmangizni tasdiqlash uchun telefon qiladi.",
    delStep3Title: "Ehtiyotkorlik bilan eltish",
    delStep3Desc: "Tuxumlar maxsus himoya qutilarida sinmasdan yetkaziladi.",
    delStep4Title: "Qulay To'lov",
    delStep4Desc: "Mahsulotni qo'lingizga olgach naqd yoki Click/Payme orqali to'laysiz.",
    contactTitle: "Savollaringiz bormi?",
    contactSub: "Biz bilan bevosita bog'laning",
    contactTg: "Telegram yozish",
    contactBot: "Telegram Botimiz",
    contactPhone: "Telefon qo'ng'iroq",
    footerText: "Tuxum Market Farg'ona — Barcha huquqlar himoyalangan",
    adminLink: "Admin Panel",
    btnReadAloud: "🔊 Ovozli eshiting",
    btnPause: "⏸ To'xtatish",
    btnResume: "▶ Davom etish",
    postsSectionTitle: "Foydali ma'lumotlar",
    postsSectionSub: "Uheyiluy tuxumlari haqida qiziqarli maqolalar",
    ttsIntro: "Maqola nomi: ",
    ttsBody: "Tafsilotlar: ",
    darkMode: "Tungi rejim",
    lightMode: "Kunduzgi rejim"
  },
  "uz-cyr": {
    brandName: "Ухейилюй Тухумлари",
    heroBadge: "✨ Фарғона бўйлаб тезкор етказиб бериш",
    heroTitle: "Тоза ва Шифобахш",
    heroTitleSpan: "Ухейилюй Тухумлари",
    heroDesc: "Қора товуқлардан олинадиган, табиат мўъжизаси бўлган шифобахш мовий-яшил тухумлар. Ёшлар ривожланиши ва кексалар саломатлиги учун бебаҳодир.",
    availableEggs: "дона мавжуд",
    pricePerEgg: "сўм / дона",
    btnOrder: "🛒 Буюртма қилиш",
    btnPickup: "📍 Олиб кетиш",
    statsHenTitle: "Соғлом товуқлар",
    statsHenDesc: "Эркин парвариш",
    statsDeliveryTitle: "24/7 Хизмат",
    statsDeliveryDesc: "Тез етказиб бериш",
    statsStockTitle: "Захира",
    statsStockDesc: "Дона мавжуд",
    whyUsTitle: "Нима учун Ухейилюй?",
    whyUsSub: "Ухейилюй тухумларининг оддий тухумдан афзалликлари",
    featHenTitle: "Табиий Эркин Товуқлар",
    featHenDesc: "Фақат табиий дори-дармонсиз, яйловда боқилган Ухейилюй зотли қора товуқлар.",
    featColorTitle: "Ноёб Мовий Қобиқ",
    featColorDesc: "Тухум қобиғининг яшил-мовий ранги табиий бўлиб, юқори микроэлементлар нишонидир.",
    featFastTitle: "Эшиккача Етказиш",
    featFastDesc: "Фарғона бўйлаб буюртмангизни эҳтиёткорлик билан хонадонингизга элтиб берамиз.",
    featPriceTitle: "Ҳамёнбоп Нарх",
    featPriceDesc: "Энг шифобахш тухумларни тўғридан-тўғри ишончли қўллардан ҳамёнбоп нархда оласиз.",
    orderTitle: "Буюртма юбориш",
    orderSub: "Қуйидаги формани тўлдиринг, тез орада сиз билан боғланамиз",
    emptyStockMsg: "😔 Ҳозирча тухум қолмади. Тез орада янги тухумлар келади!",
    lowStockMsg: "⚠️ Кам қолди! Буюртма беришга шошилинг.",
    labelName: "Исмингиз",
    placeholderName: "Масалан: Алибек",
    labelPhone: "Телефон рақамингиз",
    placeholderPhone: "+998 XX XXX XX XX",
    labelAddress: "Етказиб бериш манзили",
    placeholderAddress: "Кўча, уй рақами, маҳалла",
    btnLocateMap: "🗺️ Харитадан",
    gmapSearchPlaceholder: "Манзилни киритинг ва қидиринг...",
    gmapConfirm: "✅ Тасдиқлаш",
    labelQuantity: "Сони (Дона)",
    totalPayment: "Жами тўлов:",
    btnSubmitOrder: "✅ Буюртма юбориш",
    btnSubmitting: "⏳ Юборилмоқда...",
    toastSuccess: "✅ Буюртма қабул қилинди! Тез орада боғланамиз 🎉",
    toastError: "❌ Илтимос, барча майдонларни тўлдиринг!",
    toastLowStock: "⚠️ Узр, захирада етарли эмас!",
    pickupTitle: "📍 Олиб кетиш манзили",
    pickupSub: "Бизнинг манзилимизга келиб, тухумларни ўзингиз олиб кетишингиз мумкин",
    pickupCardTitle: "📌 Манзилимиз",
    btnCall: "📞 Қўнғироқ",
    btnGmaps: "Google Maps харитаси",
    deliveryTitle: "Етказиб бериш жараёни",
    deliverySub: "Сизнинг буюртмангиз уйингизга қандай етиб боради?",
    delStep1Title: "Буюртма бериш",
    delStep1Desc: "Сайтдан ёки Телеграм бот орқали буюртма қолдирасиз.",
    delStep2Title: "Боғланиш",
    delStep2Desc: "Операторимиз буюртмангизни тасдиқлаш учун телефон қилади.",
    delStep3Title: "Эҳтиёткорлик билан элтиш",
    delStep3Desc: "Тухумлар махсус ҳимоя қутиларида синмасдан етказилади.",
    delStep4Title: "Қулай Тўлов",
    delStep4Desc: "Маҳсулотни қўлингизга олгач нақд ёки Click/Payme орқали тўлайсиз.",
    contactTitle: "Саволларингиз борми?",
    contactSub: "Биз билан бевосита боғланинг",
    contactTg: "Телеграм ёзиш",
    contactBot: "Телеграм Ботимиз",
    contactPhone: "Телефон қўнғироқ",
    footerText: "Тухум Маркет Фарғона — Барча ҳуқуқлар ҳимояланган",
    adminLink: "Админ Панел",
    btnReadAloud: "🔊 Овозли эшитинг",
    btnPause: "⏸ Тўхтатиш",
    btnResume: "▶ Давом этиш",
    postsSectionTitle: "Фойдали маълумотлар",
    postsSectionSub: "Ухейилюй тухумлари ҳақида қизиқарли мақолалар",
    ttsIntro: "Мақола номи: ",
    ttsBody: "Тафсилотлар: ",
    darkMode: "Тунги режим",
    lightMode: "Кундузги режим"
  },
  ru: {
    brandName: "Яйца Ухейилюй",
    heroBadge: "✨ Быстрая доставка по Фергане",
    heroTitle: "Чистые и Лечебные",
    heroTitleSpan: "Яйца Ухейилюй",
    heroDesc: "Целебные зелено-голубые яйца от уникальных черных кур. Настоящее чудо природы, незаменимое для развития детей и здоровья пожилых людей.",
    availableEggs: "шт. в наличии",
    pricePerEgg: "сум / шт.",
    btnOrder: "🛒 Заказать яйца",
    btnPickup: "📍 Самовывоз",
    statsHenTitle: "Здоровые куры",
    statsHenDesc: "Свободный выгул",
    statsDeliveryTitle: "Служба 24/7",
    statsDeliveryDesc: "Быстрая доставка",
    statsStockTitle: "Запас",
    statsStockDesc: "яиц в наличии",
    whyUsTitle: "Почему Ухейилюй?",
    whyUsSub: "Преимущества яиц Ухейилюй перед обычными яйцами",
    featHenTitle: "Натуральный Свободный Выгул",
    featHenDesc: "Черные куры породы Ухейилюй содержатся на свободном выпасе и питаются исключительно натуральными кормами.",
    featColorTitle: "Уникальная Зеленая Скорлупа",
    featColorDesc: "Зеленовато-голубой цвет скорлупы является естественным признаком высокого содержания микроэлементов.",
    featFastTitle: "Доставка до Двери",
    featFastDesc: "Мы бережно и быстро доставим ваш заказ в любую точку Ферганы в специальной защитной упаковке.",
    featPriceTitle: "Доступная Цена",
    featPriceDesc: "Вы получаете целебный продукт напрямую из надежных рук по оптимальной и честной цене.",
    orderTitle: "Оформить заказ",
    orderSub: "Заполните форму ниже, и мы свяжемся с вами в ближайшее время",
    emptyStockMsg: "😔 Извините, яйца закончились. Скоро будет новая поставка!",
    lowStockMsg: "⚠️ Осталось мало! Поторопитесь с заказом.",
    labelName: "Ваше имя",
    placeholderName: "Например: Алибек",
    labelPhone: "Номер телефона",
    placeholderPhone: "+998 XX XXX XX XX",
    labelAddress: "Адрес доставки",
    placeholderAddress: "Улица, дом, ориентир",
    btnLocateMap: "🗺️ На карте",
    gmapSearchPlaceholder: "Введите адрес для поиска...",
    gmapConfirm: "✅ Подтвердить",
    labelQuantity: "Количество (шт.)",
    totalPayment: "Итого к оплате:",
    btnSubmitOrder: "✅ Отправить заказ",
    btnSubmitting: "⏳ Отправка...",
    toastSuccess: "✅ Заказ принят! Мы скоро свяжемся с вами 🎉",
    toastError: "❌ Пожалуйста, заполните все поля!",
    toastLowStock: "⚠️ Недостаточно товара на складе!",
    pickupTitle: "📍 Точка самовывоза",
    pickupSub: "Вы можете приехать по нашему адресу и забрать яйца самостоятельно",
    pickupCardTitle: "📌 Наш адрес",
    btnCall: "📞 Позвонить",
    btnGmaps: "Карта Google Maps",
    deliveryTitle: "Процесс доставки",
    deliverySub: "Как ваш заказ доставляется на дом?",
    delStep1Title: "Оформление",
    delStep1Desc: "Вы оставляете заявку на сайте или через нашего Telegram-бота.",
    delStep2Title: "Подтверждение",
    delStep2Desc: "Наш оператор связывается с вами по телефону для подтверждения заказа.",
    delStep3Title: "Бережная перевозка",
    delStep3Desc: "Яйца упаковываются в специальные ударопрочные лотки.",
    delStep4Title: "Удобная Оплата",
    delStep4Desc: "Оплата производится при получении наличными или через Click/Payme.",
    contactTitle: "Остались вопросы?",
    contactSub: "Свяжитесь с нами напрямую",
    contactTg: "Написать в Telegram",
    contactBot: "Наш Telegram-бот",
    contactPhone: "Позвонить по телефону",
    footerText: "Tuxum Market Fergana — Все права защищены",
    adminLink: "Админ-Панель",
    btnReadAloud: "🔊 Прослушать аудио",
    btnPause: "⏸ Пауза",
    btnResume: "▶ Продолжить",
    postsSectionTitle: "Полезная информация",
    postsSectionSub: "Интересные статьи о пользе яиц Ухейилюй",
    ttsIntro: "Название статьи: ",
    ttsBody: "Подробности: ",
    darkMode: "Темный режим",
    lightMode: "Светлый режим"
  },
  en: {
    brandName: "Uheyiluy Eggs",
    heroBadge: "✨ Fast Delivery across Fergana",
    heroTitle: "Pure & Medicinal",
    heroTitleSpan: "Uheyiluy Eggs",
    heroDesc: "Healing green-blue eggs from unique black chickens. A true miracle of nature, essential for children's brain development and elderly health.",
    availableEggs: "eggs available",
    pricePerEgg: "UZS / egg",
    btnOrder: "🛒 Order Eggs",
    btnPickup: "📍 Pickup",
    statsHenTitle: "Healthy Hens",
    statsHenDesc: "Free-range pasture",
    statsDeliveryTitle: "24/7 Service",
    statsDeliveryDesc: "Fast local delivery",
    statsStockTitle: "Stock Level",
    statsStockDesc: "eggs available",
    whyUsTitle: "Why Uheyiluy?",
    whyUsSub: "Advantages of Uheyiluy eggs compared to ordinary chicken eggs",
    featHenTitle: "Natural Free Range",
    featHenDesc: "Our black chickens range freely and are fed 100% natural organic food with no chemicals.",
    featColorTitle: "Unique Blue Shell",
    featColorDesc: "The beautiful pale green-blue shell is a natural indicator of exceptionally high mineral levels.",
    featFastTitle: "Doorstep Delivery",
    featFastDesc: "We carefully deliver your order directly to your door in Fergana using shock-absorbent packaging.",
    featPriceTitle: "Affordable Pricing",
    featPriceDesc: "Get the most medicinal organic eggs straight from a trusted farm at a reasonable, honest price.",
    orderTitle: "Submit Order",
    orderSub: "Fill in the form below and we will contact you shortly to confirm",
    emptyStockMsg: "😔 Sorry, we are out of stock! New fresh eggs are coming soon.",
    lowStockMsg: "⚠️ Limited Stock! Order quickly before we run out.",
    labelName: "Your Name",
    placeholderName: "Example: Alibek",
    labelPhone: "Phone Number",
    placeholderPhone: "+998 XX XXX XX XX",
    labelAddress: "Delivery Address",
    placeholderAddress: "Street, House, District",
    btnLocateMap: "🗺️ On Map",
    gmapSearchPlaceholder: "Search for your location...",
    gmapConfirm: "✅ Confirm Location",
    labelQuantity: "Quantity (eggs)",
    totalPayment: "Total Payment:",
    btnSubmitOrder: "✅ Place Order",
    btnSubmitting: "⏳ Submitting...",
    toastSuccess: "✅ Order received! We will contact you soon 🎉",
    toastError: "❌ Please fill in all required fields!",
    toastLowStock: "⚠️ Sorry, not enough stock left!",
    pickupTitle: "📍 Self-Pickup Point",
    pickupSub: "You can visit our location to pick up your fresh eggs directly",
    pickupCardTitle: "📌 Our Location",
    btnCall: "📞 Call Us",
    btnGmaps: "Open in Google Maps",
    deliveryTitle: "Delivery Process",
    deliverySub: "How your order gets delivered to your home",
    delStep1Title: "Place Order",
    delStep1Desc: "Place your order on this website or through our Telegram bot.",
    delStep2Title: "Confirmation",
    delStep2Desc: "Our manager calls you via phone to confirm your delivery details.",
    delStep3Title: "Safe Transit",
    delStep3Desc: "We pack your fresh eggs in premium shock-proof protective boxes.",
    delStep4Title: "Easy Payment",
    delStep4Desc: "Pay on delivery using cash or popular local methods (Click/Payme).",
    contactTitle: "Any Questions?",
    contactSub: "Feel free to get in touch with us",
    contactTg: "Message on Telegram",
    contactBot: "Our Telegram Bot",
    contactPhone: "Call Our Farm",
    footerText: "Tuxum Market Fergana — All rights reserved",
    adminLink: "Admin Dashboard",
    btnReadAloud: "🔊 Read Aloud",
    btnPause: "⏸ Pause",
    btnResume: "▶ Resume",
    postsSectionTitle: "Medicinal Benefits",
    postsSectionSub: "Fascinating articles about organic Uheyiluy eggs",
    ttsIntro: "Article Title: ",
    ttsBody: "Details: ",
    darkMode: "Dark Mode",
    lightMode: "Light Mode"
  }
};
